Match Markdown relative images and replace them with data URIs
Truebill/smcms pull request #3
Opened 2016-09-08 19:13 UTC by stevehollaar

2016-09-08 20:11 UTC, idris commented
A few things:

1. Perhaps we should add abstractions for value => html rendering, so that it'll get configured with a map of extensions => processors.  Markdown would be one of those, and would run it through `marked`.
2. Perhaps the replacement of relative images (or file references) should also be configurable, so that we can use data-URIs or http URLs that will be hosted on a CDN.  This would be orthogonal to the markdown processor because it would work for other formats like textile, html, etc.  It would be a simple API of `(filePath) => Promise<fileUrl>`
3. I thought we decided against data-URIs for our internal use.

2016-09-08 21:16 UTC, idris commented on src/stores/GithubStore.js
> +  async getValueFromPath(objectPath, decode = true) {
Two things here:
1. Should this return a `Stream`? Or does Buffer also avoid forcing the entire file into memory?
2. Maybe this should be named something like `streamBinaryFromPath` to make clear that this is for getting raw binary data from the store.

2016-09-13 20:41 UTC, idris commented on src/stores/GithubStore.js
> +        return this.renderer.render(content, {
I think we can keep this outside of the store, and get rid of the `selfRenders` option.  We always know the `contentPath` outside of the store, and the store can still expose `getContentFromPath`.

2016-09-14 18:45 UTC, idris requested changes
@stevehollaar see https://github.com/Truebill/smcms/pull/3#r78640019

2016-09-15 21:04 UTC, stevehollaar commented
### Planned changes

**Content paths:**
 - `/` separated
 - include file extensions

**SMCS:**
- instantiated with:
 - `getRenderer` method (optional)
   - defaults to map of file extensions to renderers (e.g. `.md` -> `new MarkdownRenderer()`), with fallback to no-op renderer
 - `store` instance (required)
 - `resolveRelativePaths` method (optional)
   - default to `path.join(path.dirname(contentPath), relativePath)`

**Stores**
 - must expose `getValue` method
 - `getValue` must return a stream

**Renderers**
 - must expose `render` method
 - `render` method operates on streams

2016-09-15 21:13 UTC, idris commented
👍
My comments:
* maybe just rename `resolveRelativePaths` to `resolveRelativePath` (singular)
* If we're not doing base64 stuff, the stream stuff becomes less necessary.  We can push that off to a later version.

2016-09-16 17:51 UTC, idris approved these changes

2016-09-16 17:51 UTC, merged

2016-09-16 17:51 UTC, idris commented
@stevehollaar merged.  Once you have it working in billninja, we can release a new version to npm